### ISSUE TITLE
Stop blocking nightlies when RLS/rustfmt/clippy is missing

### ISSUE THREAD

**Issue by kennytm** [rust-lang/promote-release#19]
We currently will not release nightlies when RLS/rustfmt/clippy is missing to avoid accidentally removing them (913a3b3650231884a6bc8ad3cd98a44e8552b45a). But this impedes use of the compiler not involving these tools e.g. CI testing and bisection.

rustup 1.12.0 (573895abc 2018-07-07) has recently been released, which according to https://github.com/rust-lang/rust-central-station/pull/61#issuecomment-402165412 should include a patch that when a component is unavailable will simply refuse to upgrade instead of removing it.

This means we could mark missing RLS/rustfmt/clippy as `available = false` instead of blocking the entire nightly.

**Comment by pietroalbini** [comment]
Everything about this issue should now be fixed!
