### ISSUE TITLE
Miri is missing from releases since the introduction of smoke tests

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/promote-release#30]
After #25 got merged Miri stopped shipping from releases. Miri is a bit special in the release process since we only ship it if the tests also pass, and to do so we rely on `toolstates-linux.json`. #25 changed the release process to be like this though:

1. ...
2. A manifest with dummy endpoints is generated (parsing `toolstates-linux.json` to decide whether to include Miri).
3. Files that are not included in the manifest are removed (removing `toolstates-linux.json`)
4. All files are hashed and signed.
5. Smoke tests are executed, installing the release through Rustup and trying to compile something.
6. A manifest with the production endpoints is generated (**BUG!** `toolstate-linux.json` was removed earlier).
7. The new manifest is hashed and signed.
8. ...

A possible solution is to move step 6 right after step 2, generating the two sets of manifests in different directories.

**Comment by RalfJung** [comment]
Another option might be to keep the JSON file around.

**Comment by pietroalbini** [comment]
Opened https://github.com/rust-lang/promote-release/pull/31 with the solution I outlined in my earlier comment!

> Another option might be to keep the JSON file around.

I kinda prefer reordering steps, to avoid making exceptions to the pruning code.

**Comment by pietroalbini** [comment]
Started a nightly release on the **staging** environment to make sure this is working. Will have results in less than an hour.

**Comment by pietroalbini** [comment]
@RalfJung confirmed the manifest now contains miri! You can test it yourself with:

```
RUSTUP_DIST_SERVER="https://dev-static.rust-lang.org" rustup update nightly
```
