### ISSUE TITLE
Fix release checksum files

### ISSUE THREAD

**Issue by dbrgn** [rust-lang/promote-release#35]
Starting with the 1.48 release, the checksum files are missing the filename:

![image](https://user-images.githubusercontent.com/105168/102187246-055dc980-3eb4-11eb-9468-7114fb6c84e4.png)

For a checksum file to work with `sha256sum -c`, the filename must be included.

**Comment by pietroalbini** [comment]
Opened https://github.com/rust-lang/promote-release/pull/36 to fix this. Once the PR is merged and a nightly has been released with it (to ensure you can reproduce the fix in prod too) I'll look into fixing the checksum files for the 1.48.0 stable release.

**Comment by Mark-Simulacrum** [comment]
Going to reopen to track fixing historical files for at least stable release.

**Comment by pietroalbini** [comment]
@dbrgn could you check whether the current nightly works on your end?

```
https://static.rust-lang.org/dist/2020-12-16/rust-nightly-x86_64-unknown-linux-gnu.tar.xz
```

**Comment by dbrgn** [comment]
```
danilo@x2000:tmp$ sha256sum -c rust-nightly-x86_64-unknown-linux-gnu.tar.xz.sha256
rust-nightly-x86_64-unknown-linux-gnu.tar.xz: OK
```

Looking good!

**Comment by pietroalbini** [comment]
Wrote [a script](https://gist.github.com/pietroalbini/b81dca51e40d7f6fdb89b523e5b76e93) to do the backfilling and executed it on `dev-static.rust-lang.org`. @dbrgn could you double-check the format works on your end (before I run the script on the production bucket) if you download the files from https://dev-static.rust-lang.org instead of https://static.rust-lang.org?

**Comment by dbrgn** [comment]
Before the change (on static.rust-lang.org):

```
$ export VERSION=1.48.0
$ $ wget https://dev-static.rust-lang.org/dist/rust-${VERSION}-x86_64-unknown-linux-gnu.tar.gz
$ wget https://static.rust-lang.org/dist/rust-${VERSION}-x86_64-unknown-linux-gnu.tar.gz.sha256
$ sha256sum -c rust-${VERSION}-x86_64-unknown-linux-gnu.tar.gz.sha256
sha256sum: rust-1.48.0-x86_64-unknown-linux-gnu.tar.gz.sha256: no properly formatted SHA256
checksum lines found
```

After the change (on dev-static.rust-lang.org):

```
$ export VERSION=1.48.0
$ wget https://dev-static.rust-lang.org/dist/rust-${VERSION}-x86_64-unknown-linux-gnu.tar.gz
$ wget https://dev-static.rust-lang.org/dist/rust-${VERSION}-x86_64-unknown-linux-gnu.tar.gz.sha256
$ sha256sum -c rust-${VERSION}-x86_64-unknown-linux-gnu.tar.gz.sha256
rust-1.48.0-x86_64-unknown-linux-gnu.tar.gz: OK
$ echo $?
0
```

So: Looking good, thak you :)

**Comment by pietroalbini** [comment]
Backfilled the hashes in static.rust-lang.org :tada:
