### ISSUE TITLE
missing sha256 file for rust-std-beta-sparcv9-sun-solaris

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/promote-release#37]
Reported by michele on i.r-l.o: https://internals.rust-lang.org/t/build-fails-at-curl-with-url-404/13651

    ...
    downloading https://static.rust-lang.org/dist/2020-11-18/rust-std-beta-sparcv9-sun-solaris.tar.gz
    ######################################################################### 100.0%
    extracting /opt/rust/build/cache/2020-11-18/rust-std-beta-sparcv9-sun-solaris.tar.gz
    curl: (22) The requested URL returned error: 404 

    spurious failure, trying again
    curl: (22) The requested URL returned error: 404 

    spurious failure, trying again
    curl: (22) The requested URL returned error: 404 

    spurious failure, trying again
    curl: (22) The requested URL returned error: 404 

    spurious failure, trying again
    curl: (22) The requested URL returned error: 404 
    failed to run: curl -s -y 30 -Y 10 --connect-timeout 30 --retry 3 -Sf -o /tmp/tmpegSRz8.sha256 https://static.rust-lang.org/dist/2020-11-18/rustc-beta-sparcv9-sun-solaris.tar.gz.sha256
    Build completed unsuccessfully in 0:07:54

**Comment by pietroalbini** [comment]
The error is happening while trying to download the `rustc` component for the `sparcv9-sun-solaris` target. That's expected to faii, as `sparcv9-sun-solaris` is a target [without host tools](https://doc.rust-lang.org/nightly/rustc/platform-support.html).

**Comment by Michele31415** [comment]
It is a bit odd that if this is the case, it should download the tar file without problems and then complain about a missing sha256 file for thzt tar file, after downloading many many megabytes of other sources.  Perhaps this could be caught earlier.  I do note that there are several posts on the web about getting a rust compiler working on Solaris SPARC.  What host tools are missing?  Perhaps I could get them.  Thanks.

**Comment by birkenfeld** [comment]
Note that the tar file is `rust-std`, which is available, while the checksum file belongs to the *next* tarfile with `rustc`.

**Comment by pietroalbini** [comment]
> What host tools are missing? Perhaps I could get them.

Rust's CI only produces the precompiled standard library for that platform, not the compiler. I'm not sure which posts you're following, but I'm not aware of host tools ever being built by CI for `sparcv9-sun-solaris`.

**Comment by Michele31415** [comment]
"the checksum file refers to the next tarfile"
OK, that explains that but
"which would contain rustc."
Pardon my confusion but isn't rustc what x.py is supposed to build?  

In https://rustc-dev-guide.rust-lang.org/building/how-to-build-and-run.html it says
"The compiler is built using a tool called x.py."
I guess I'm still missing something here.

**Comment by birkenfeld** [comment]
The compiler is written in Rust, so it needs a previously built binary rustc to compile itself.

To bootstrap, you'd probably have to cross-compile rustc for your target on a supported host, and then tell `x.py` to use that compiler as the bootstrap compiler.  How you would do that, I have no idea...
